language: ruby
cache: bundler
services:
  - redis-server
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - 2.7.0
#  - ruby-head
